[pytest]
testpaths = tests
pythonpath = app/backend
norecursedirs =
    archive
    output
    logs
    tmp
    .git
    .venv
    venv
    node_modules
    _darcs
    build
    CVS
    dist
    *.egg
    .*
    {arch}
